/** Popular cities from Peekaboo bank locators */
export const PEEKABOO_POPULAR_CITIES = [
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Faisalabad',
  'Peshawar',
  'Quetta',
  'Sialkot',
] as const;

/** All "Other Cities" from Peekaboo UI */
export const PEEKABOO_OTHER_CITIES = [
  'Multan',
  'Sukkur',
  'Gujranwala',
  'Hyderabad',
  'Sargodha',
  'Bahawalpur',
  'Arifwala',
  'Bahawalnagar',
  'Burewala',
  'Chakwal',
  'Chiniot',
  'Dadu',
  'Dera Ismail Khan',
  'Jhelum',
  'Kabirwala',
  'Kotli',
  'Lodhran',
  'Mailsi',
  'Mardan',
  'Mianwali',
  'Sadiqabad',
  'Sheikhupura',
  'Sambrial',
  'Chaman',
  'Murree',
  'Renala Khurd',
  'Skardu',
  'Mirpur Mathelo',
  'Hunza',
  'Mirpur Khas',
  'Timergara',
  'Gujrat',
  'Haripur',
  'Hasilpur',
  'Jaranwala',
  'Kahuta',
  'Kasur',
  'Khanewal',
  'Khushab',
  'Kohat',
  'Mansehra',
  'Mian Channu',
  'Mirpur Azad Kashmir',
  'Muzaffargarh',
  'Nowshera',
  'Okara',
  'Pattoki',
  'Phalia',
  'Rahimyar Khan',
  'Rajanpur',
  'Sahiwal',
  'Sanghar',
  'Shahdadpur',
  'Tando Adam',
  'Toba Tek Singh',
  'Wazirabad',
  'Nankana Sahib',
  'Kandhkot',
  'Chitral',
  'Bhakkar',
  'Ghazi',
  'Kallar Syedan',
  'Turbat',
  'Batkhela',
  'Talagang',
  'Shahkot',
  'Kot Abdul Malik',
  'Swat',
  'Abbottabad',
  'Attock',
  'Bannu',
  'Charsadda',
  'Chichawatni',
  'Chishtian',
  'Daska',
  'Dera Ghazi Khan',
  'Dina',
  'Ghotki',
  'Gilgit',
  'Gojra',
  'Gujar Khan',
  'Hafizabad',
  'Haroonabad',
  'Havelian',
  'Jacobabad',
  'Jhang',
  'Khanpur',
  'Kharian',
  'Kot Addu',
  'Larkana',
  'Layyah',
  'Mandi Bahauddin',
  'Muzaffarabad',
  'Narowal',
  'Nawabshah',
  'Pakpattan',
  'Pishin',
  'Swabi',
  'Vehari',
  'Muridke',
  'Gwadar',
  'Battagram',
  'Loralai',
  'Pindigheb',
  'Sibi',
  'Hangu',
  'Sakhakot',
  'Pallandri',
  'Astore',
  'Bagh',
  'Badin',
  'Bahrain',
  'Bajaur Agency',
  'Barikot',
  'Barkhan',
  'Basti Malook',
  'Bhimber',
  'Buner',
  'Chagai',
  'Bara',
  'Chilas',
  'Chunian',
  'Dadyal',
  'Dargai',
  'Darra Adam Khel',
  'Darya Khan',
  'Dera Bugti',
  'Dera Murad Jamali',
  'Diamir',
  'Dir',
  'Dunyapur',
  'Fazilpur',
  'Fort Abbas',
  'Hajira',
  'Harnai',
  'Hattian Bala',
  'Haveli Azad Kashmir',
  'Hub',
  'Jaffarabad',
  'Jalalpur Pirwala',
  'Jamrud',
  'Jamshoro',
  'Jhal Magsi',
  'Kabal',
  'Kachhi',
  'Kalat',
  'Karak',
  'Kashmore',
  'Zhob',
  'Yaka Ghund',
  'Usta Mohammad',
  'Upper Dir',
  'Umerkot',
  'Tor Ghar',
  'Topi',
  'Thatta',
  'Tharparkar',
  'Taunsa',
  'Tank',
  'Tando Muhammad Khan',
  'Tando Allahyar',
  'Takht Bhai',
  'Sujawal',
  'Sudhanoti',
  'South Waziristan',
  'Sohbatpur',
  'Sohawa',
  'Sillanwali',
  'Shujaabad',
  'Shikarpur',
  'Sharaqpur',
  'Shangla',
  'Shahdadkot',
  'Shabqadar',
  'Rawalakot',
  'Raiwind',
  'Qila Saifullah',
  'Qila Abdullah',
  'Qambar',
  'Qadirpur Ran',
  'Poonch',
  'Piplan',
  'Pindi Bhattian',
  'Phool Nagar',
  'Parachinar',
  'Panjgur',
  'Painsra',
  'Paharpur',
  'Pabbi',
  'Orakzai Agency',
  'Oghi City',
  'Nushki',
  'North Waziristan',
  'Noor Shah',
  'Neelam Valley',
  'Naushahro Feroze',
  'Musa Khel',
  'Mohmand Agency',
  'Mithi',
  'Miro Khan',
  'Mingora',
  'Minchinabad',
  'Mehar',
  'Matta',
  'Matiari',
  'Mastung',
  'Mand Kech',
  'Malakand',
  'Lower Dir',
  'Liaquatpur',
  'Lehri',
  'Lasbela',
  'Lakki Marwat',
  'Kurram Agency',
  'Kuchlak',
  'Kotri',
  'Kot Radha Kishan',
  'Kot Chutta',
  'Kohlu',
  'Kohistan',
  'Khyber Agency',
  'Khuzdar',
  'Khuiratta',
  'Khar',
  'Khaplu',
  'Khanozai',
  'Khairpur',
  'Pahrianwali',
  'Maroot',
  'Khan Bela',
  'Pasrur',
  'Wah Cantt',
] as const;

function dedupeCityNames(names: readonly string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];

  for (const name of names) {
    const trimmed = name.trim();
    const key = trimmed.toLowerCase();
    if (!trimmed || seen.has(key)) continue;
    seen.add(key);
    result.push(trimmed);
  }

  return result;
}

/** Full Peekaboo city list (popular + other, deduplicated) */
export const PEEKABOO_CITIES_FULL = dedupeCityNames([
  ...PEEKABOO_POPULAR_CITIES,
  ...PEEKABOO_OTHER_CITIES,
]);
